# Generated by Django 5.2.4 on 2025-08-05 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAdvert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("company_name", models.CharField(max_length=150)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry_level", "Entry Level"),
                            ("mid_level", "Mid Level"),
                            ("senior_level", "Senior Level"),
                            ("executive", "Executive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("on_site", "On Site"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("deadline", models.DateTimeField()),
                ("skills", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                ("resume", models.FileField(upload_to="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "APPLIED"),
                            ("INTERVIEW_SCHEDULED", "INTERVIEW_SCHEDULED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="APPLIED",
                        max_length=50,
                    ),
                ),
                (
                    "job_advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="job_application.jobadvert",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
